ALTER TABLE "Tenant" ADD COLUMN "headerLayout" TEXT NOT NULL DEFAULT 'classic';
ALTER TABLE "TenantProfile" ADD COLUMN "headerShowPhone" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "TenantProfile" ADD COLUMN "headerTaglineKk" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "headerTaglineRu" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "headerCtaTextKk" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "headerCtaTextRu" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "headerCtaUrl" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroEyebrowKk" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroEyebrowRu" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroTitleKk" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroTitleRu" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroHighlightKk" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroHighlightRu" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroLeadKk" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroLeadRu" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroCta1TextKk" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroCta1TextRu" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroCta1Url" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroCta2TextKk" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroCta2TextRu" TEXT;
ALTER TABLE "TenantProfile" ADD COLUMN "heroCta2Url" TEXT;
