ALTER TABLE "Tenant" ADD COLUMN "headerSticky" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tenant" ADD COLUMN "homeShowSections" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Tenant" ADD COLUMN "homeSectionIds" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Tenant" ADD COLUMN "homeShowContacts" BOOLEAN NOT NULL DEFAULT true;
